BEGIN;
CREATE TABLE IF NOT EXISTS api_keys (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, key_hash TEXT NOT NULL UNIQUE, label TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), revoked_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS api_keys_user_idx ON api_keys(user_id);
INSERT INTO schema_migrations(version) VALUES ('003_auth') ON CONFLICT DO NOTHING;
COMMIT;