import type { FastifyInstance } from 'fastify';
import type { PolicyRule } from '@axsd/core';
const policies:Array<PolicyRule & {ownerId:string}> = [];
function validPolicy(body: unknown): body is PolicyRule { const p=body as Partial<PolicyRule>|null; return !!p && typeof p==='object' && typeof p.id==='string' && !!p.id.trim() && typeof p.name==='string' && !!p.name.trim(); }
export function registerPolicyRoutes(app:FastifyInstance):void{
 app.get('/api/v1/policies',async(request,reply)=>{const ownerId=request.principal?.id;if(!ownerId)return reply.status(401).send({error:{code:'AUTH_ERR',message:'Authentication required'}});return{data:policies.filter(p=>p.ownerId===ownerId).map(({ownerId:_ownerId,...p})=>p)}});
 app.get<{Params:{id:string}}>('/api/v1/policies/:id',async(request,reply)=>{const ownerId=request.principal?.id;if(!ownerId)return reply.status(401).send({error:{code:'AUTH_ERR',message:'Authentication required'}});const p=policies.find(x=>x.ownerId===ownerId&&x.id===request.params.id);if(!p)return reply.status(404).send({error:{code:'NOT_FOUND',message:'Policy not found'}});const {ownerId:_ownerId,...safe}=p;return{data:safe};});
 app.post<{Body:PolicyRule}>('/api/v1/policies',async(request,reply)=>{const ownerId=request.principal?.id;if(!ownerId)return reply.status(401).send({error:{code:'AUTH_ERR',message:'Authentication required'}});if(!validPolicy(request.body))return reply.status(400).send({error:{code:'VALIDATION_ERR',message:'Policy id and name are required'}});if(policies.some(p=>p.id===request.body.id.trim()&&p.ownerId===ownerId))return reply.status(409).send({error:{code:'CONFLICT',message:'Policy already exists'}});const policy={...request.body,id:request.body.id.trim(),name:request.body.name.trim(),ownerId};policies.push(policy);return reply.status(201).send({data:request.body});});
 app.delete<{Params:{id:string}}>('/api/v1/policies/:id',async(request,reply)=>{const ownerId=request.principal?.id;if(!ownerId)return reply.status(401).send({error:{code:'AUTH_ERR',message:'Authentication required'}});const index=policies.findIndex(p=>p.ownerId===ownerId&&p.id===request.params.id);if(index<0)return reply.status(404).send({error:{code:'NOT_FOUND',message:'Policy not found'}});policies.splice(index,1);return reply.status(204).send();});
}
