import type { FastifyInstance } from 'fastify';
import { PostgresProjectRepository, createPool } from '@axsd/storage';
type Project={id:string;ownerId:string;name:string;instructions?:string;status:'ACTIVE'|'ARCHIVED';createdAt:string};
const memory:Project[]=[];
export function registerProjectRoutes(app:FastifyInstance):void{
 const owner=async(request:any,reply:any)=>{const id=request.principal?.id;if(!id)return reply.status(401).send({error:{code:'AUTH_ERR',message:'Authentication required'}});return id};
 app.get<{Params:{id:string}}>('/api/v1/projects/:id',async(request,reply)=>{const ownerId=await owner(request,reply);if(!ownerId)return; if(process.env.DATABASE_URL){const pool=createPool();try{const p=await new PostgresProjectRepository(pool).get(request.params.id);if(!p||p.ownerId!==ownerId)return reply.status(404).send({error:{code:'NOT_FOUND',message:'Project not found'}});return{data:p}}finally{await pool.end();}}const p=memory.find(x=>x.id===request.params.id&&x.ownerId===ownerId);if(!p)return reply.status(404).send({error:{code:'NOT_FOUND',message:'Project not found'}});return{data:p}});
 app.get('/api/v1/projects',async(request,reply)=>{const ownerId=await owner(request,reply);if(!ownerId)return;if(process.env.DATABASE_URL){const pool=createPool();try{return{data:await new PostgresProjectRepository(pool).list(ownerId)}}finally{await pool.end();}}return{data:memory.filter(p=>p.ownerId===ownerId)}});
 app.post<{Body:{name:string;instructions?:string}}>('/api/v1/projects',async(request,reply)=>{const ownerId=await owner(request,reply);if(!ownerId)return;const body=request.body;if(typeof body?.name!=='string'||!body.name.trim()||(body.instructions!==undefined&&typeof body.instructions!=='string'))return reply.status(400).send({error:{code:'VALIDATION_ERR',message:'Invalid project definition'}});const project={id:crypto.randomUUID(),ownerId,name:body.name.trim(),instructions:body.instructions,status:'ACTIVE' as const,createdAt:new Date().toISOString()};if(process.env.DATABASE_URL){const pool=createPool();try{await new PostgresProjectRepository(pool).create(project);return reply.status(201).send({data:project})}finally{await pool.end()}}memory.push(project);return reply.status(201).send({data:project})});
}
